title: Tariqul Design
description: Graphic Designer

url: https://topuhit.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: topuhit
   twitter: topuhit
   facebook: topuhit
   email: topu.hit@gmail.com

google_analytics: "UA-100807398-1"
